# Generated by Django 4.1.7 on 2023-03-30 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_alter_group_subgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('weekday', models.SmallIntegerField(choices=[(1, 'Пн'), (2, 'Вт'), (3, 'Ср'), (4, 'Чт'), (5, 'Пт'), (6, 'Сб'), (7, 'Вс')])),
                ('week', models.SmallIntegerField(choices=[(1, 'Нечетная неделя'), (2, 'Четная неделя')])),
                ('time', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('type', models.SmallIntegerField(choices=[(1, 'пр. занятие'), (2, 'лекция')])),
                ('place', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=255)),
                ('sync', models.SmallIntegerField(choices=[(1, 'синхронно'), (2, 'асинхронно')])),
                ('group', models.ManyToManyField(to='user.group')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.teacher')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятие',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_check', models.DateTimeField(auto_created=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Посещаемость',
            },
        ),
    ]
