# Generated by Django 4.1.7 on 2023-05-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_date_create'),
        ('lesson', '0003_alter_attendance_datetime_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.ManyToManyField(related_name='groups', to='user.group'),
        ),
    ]
