# Generated by Django 4.1.7 on 2023-05-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_date_create'),
        ('lesson', '0005_alter_lesson_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.ManyToManyField(related_name='groups', related_query_name='groups', to='user.group'),
        ),
    ]
