# Generated by Django 4.1.7 on 2023-03-23 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_student_user_alter_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='job_title',
        ),
    ]
