# Generated by Django 4.1.7 on 2023-03-25 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_teacher_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='refresh_token',
        ),
    ]
