# Generated by Django 4.1.7 on 2023-03-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_group_subgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='subgroup',
            field=models.SmallIntegerField(choices=[(1, '1 подгруппа'), (2, '2 подгруппа')], default=1),
        ),
    ]
