# Generated by Django 4.1.7 on 2023-04-21 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_group_subgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_create',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 4, 21, 21, 51, 24, 409183)),
            preserve_default=False,
        ),
    ]
