# Generated by Django 4.1.7 on 2023-04-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
